version: "3.8"

services:
  frontend:
    build:
      context: ./web
      dockerfile: Dockerfile
      target: runner
    container_name: neonlink-web
    ports:
      - "3000:3000"
    env_file:
      - ./web/.env
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
      - NEXT_PUBLIC_API_URL=http://localhost:5001
    restart: unless-stopped
    depends_on:
      - backend
    networks:
      - app-network
    user: "1001"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: neonlink-api
    ports:
      - "5001:5001"
    env_file:
      - ./backend/.env
    environment:
      - NODE_ENV=production
      - PORT=5001
    restart: unless-stopped
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  app-network:
    driver: bridge
