import type { Metadata } from "next";

import "./globals.css";
import { ThemeProvider } from "next-themes";
import Background from "@/components/background";
import AppNavbar from "@/components/navigation/app-navbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <ThemeProvider
          attribute="class"
          defaultTheme="light"
          enableSystem
          disableTransitionOnChange
        >
          <main className="relative">
            {/* Fixed Cyberpunk background with grid lines */}
            <Background />
            <AppNavbar />
            {children}
          </main>
        </ThemeProvider>
      </body>
    </html>
  );
}
