import type { Metadata } from "next";

import "./globals.css";
import { ThemeProvider } from "next-themes";
import { Montserrat, Audiowide } from "next/font/google";

import QueryClientProviderWrapper from "@/components/provider/query-client-wraper";
import { FloatingDock } from "@/components/navigation/floating-dock";
import { TransitionProvider } from "@/components/provider/page-transition-provider";
import { AuthProvider } from "@/contexts/auth-context";
import { BottomNav } from "@/components/navigation/mobile/bottom-nav";
import { AppBarWithTabs } from "../components/navigation/mobile/app-bar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const montserrat = Montserrat({
  subsets: ["latin"],
  variable: "--font-montserrat",
});

const audiowide = Audiowide({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-audiowide",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${montserrat.variable} ${audiowide.variable}`}>
      <body>
        <ThemeProvider
          attribute="class"
          defaultTheme="light"
          enableSystem
          disableTransitionOnChange
        >
          <QueryClientProviderWrapper>
            <TransitionProvider>
              <AuthProvider>
                <main className="relative ">
                  <AppBarWithTabs />
                  <BottomNav />
                  <div className="pt-6 pb-14 md:pt-0 md:pb-0">{children}</div>
                  <FloatingDock
                    desktopClassName="fixed bottom-6 right-6 z-50"
                    mobileClassName="fixed bottom-6 right-6 z-50"
                  />
                </main>
              </AuthProvider>
            </TransitionProvider>
          </QueryClientProviderWrapper>
        </ThemeProvider>
      </body>
    </html>
  );
}
