import type { Metadata } from "next";

import "./globals.css";
import { ThemeProvider } from "next-themes";

// import AppNavbar from "@/components/navigation/app-navbar";
import QueryClientProviderWrapper from "@/components/provider/query-client-wraper";
import { FloatingDock } from "@/components/navigation/floating-dock";
import { TransitionProvider } from "@/components/provider/page-transition-provider";
import { AuthProvider } from "@/contexts/auth-context";
// import BottomNav from "@/components/navigation/bottom-nav";
// import BackgroundV2 from "@/components/background-v2";
// import Background from "@/components/background";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <ThemeProvider
          attribute="class"
          defaultTheme="light"
          enableSystem
          disableTransitionOnChange
        >
          <QueryClientProviderWrapper>
            <TransitionProvider>
              <AuthProvider>
                <main className="relative ">
                  {/* Fixed Cyberpunk background with grid lines */}
                  {/* <Background /> */}
                  {children}
                  <FloatingDock
                    desktopClassName="fixed bottom-6 right-6 z-50"
                    mobileClassName="fixed bottom-6 right-6 z-50"
                  />
                </main>
              </AuthProvider>
            </TransitionProvider>
          </QueryClientProviderWrapper>
        </ThemeProvider>
      </body>
    </html>
  );
}
